### ISSUE TITLE
Callback in Object properties does not fire

### ISSUE THREAD

**Issue by thboomsma** [ValYouW/jqPropertyGrid#23]
In your example you have a callback function.
I have been trying to get callbacks working on each changed property to create a "live view" of changes in a control.

What am I missing or is this my environment? Chrome latest version.

PS: Awesome lightweight tool.. love it even 8 years since its inception I still use it
Cheers
T

**Comment by ValYouW** [comment]
Hi,
Wow, I actually started working on it 10 years ago :)
I updated the demo codepen to include handling of the `callback` prop, you can see it working [here](https://codepen.io/ValYouW/pen/ExrPEv).

Note though that I am using jquery 2.1.3 while the current jquery is 3.7.1, so I really don't know if this little tool will work with the latest jquery....

**Comment by thboomsma** [comment]
I can confirm that the callback works, even with the latest JQuery version.
I was flattening a nested Configuration object and loading it with path.keyname:value which was accepted by the UI but obviously not by the callback handler. I changed the divider to "_" and all works fine now
What I am trying to create is jqPropertyGrid support for a NestedObject config by creating group headers for each parent path and loading the end-points in these groups  .. any pointers for that?
