### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by ebonwheeler** [ValYouW/jqPropertyGrid#7]
At the moment, it looks like the layout of the property grid is dependent on the sort order of the fields in the object. This close coupling causes problems as objects could have their fields sorted. 

Is there a way of defining the order of fields in the property grid? Or a flag to make the order dependent on the meta object instead as this is guaranteed to not change?

**Comment by ValYouW** [comment]
Hi, there is no way to control the order of the fields in the gui, it just iterates over the target object properties...

**Comment by asimov6** [comment]
Could you give me an example as how to retrieve the current values from the propertygrid?

**Comment by ValYouW** [comment]
PR #19 added option to add a sort function to control the order of the property grid
